spring:
  application:
    name: DeveloperPilotProject
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/developerpilotproject
    username: root
    password: 00Mishr@
  sql:
    init:
      mode: always
  batch:
    jdbc:
      initialize-schema: always
  flyway:
    enabled: true
    locations: classpath:db/migrations
    baseline-on-migrate: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics

logging:
  level:
    org:
      springframework:
        security: DEBUG
springdoc:
  swagger-ui:
    csrf:
      enabled: false
